import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { BookingProvider } from "@/context/BookingContext";
import { SearchProvider } from "@/context/SearchContext";
import { WishlistProvider } from "@/context/WishlistContext";
import Navbar from "@/components/page/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <WishlistProvider>
            <SearchProvider>
              <BookingProvider>
                <Navbar />
                {children}
              </BookingProvider>
            </SearchProvider>
          </WishlistProvider>
        </ThemeProvider>
      </body> 

    </html>
  );
}
